# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'spectWindow2.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_spectWindow2(object):
    def setupUi(self, spectWindow2):
        spectWindow2.setObjectName("spectWindow2")
        spectWindow2.resize(575, 445)
        self.gridLayout = QtWidgets.QGridLayout(spectWindow2)
        self.gridLayout.setObjectName("gridLayout")
        self.spectView2 = QtWidgets.QLabel(spectWindow2)
        self.spectView2.setText("")
        self.spectView2.setObjectName("spectView2")
        self.gridLayout.addWidget(self.spectView2, 0, 0, 1, 1)

        self.retranslateUi(spectWindow2)
        QtCore.QMetaObject.connectSlotsByName(spectWindow2)
        spectWindow2.setStyleSheet("QMainWindow{\n"
"\n"
"\n"
"\n"
"}\n"
"\n"

"QWidget\n"
"{\n"
"background-color:  #d4d5dd;"
"}\n"
"\n"
"")

    def retranslateUi(self, spectWindow2):
        _translate = QtCore.QCoreApplication.translate
        spectWindow2.setWindowTitle(_translate("spectWindow2", "Channel 2"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    spectWindow2 = QtWidgets.QWidget()
    ui = Ui_spectWindow2()
    ui.setupUi(spectWindow2)
    spectWindow2.show()
    sys.exit(app.exec_())
