# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'spectWindow3.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_spectWindow3(object):
    def setupUi(self, spectWindow3):
        spectWindow3.setObjectName("spectWindow3")
        spectWindow3.resize(575, 445)
        self.gridLayout = QtWidgets.QGridLayout(spectWindow3)
        self.gridLayout.setObjectName("gridLayout")
        self.spectView3 = QtWidgets.QLabel(spectWindow3)
        self.spectView3.setText("")
        self.spectView3.setObjectName("spectView3")
        self.gridLayout.addWidget(self.spectView3, 0, 0, 1, 1)

        self.retranslateUi(spectWindow3)
        QtCore.QMetaObject.connectSlotsByName(spectWindow3)
        spectWindow3.setStyleSheet("QMainWindow{\n"
"\n"
"\n"
"\n"
"}\n"
"\n"

"QWidget\n"
"{\n"
"background-color:  #d4d5dd;"
"}\n"
"\n"
"")

    def retranslateUi(self, spectWindow3):
        _translate = QtCore.QCoreApplication.translate
        spectWindow3.setWindowTitle(_translate("spectWindow3", "Channel 3"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    spectWindow3 = QtWidgets.QWidget()
    ui = Ui_spectWindow3()
    ui.setupUi(spectWindow3)
    spectWindow3.show()
    sys.exit(app.exec_())
