# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'spectWindow1.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_spectWindow1(object):
    def setupUi(self, spectWindow1):
        spectWindow1.setObjectName("spectWindow1")
        spectWindow1.resize(575, 445)
        self.gridLayout = QtWidgets.QGridLayout(spectWindow1)
        self.gridLayout.setObjectName("gridLayout")
        self.spectView1 = QtWidgets.QLabel(spectWindow1)
        self.spectView1.setObjectName("spectView1")
        self.gridLayout.addWidget(self.spectView1, 0, 0, 1, 1)

        self.retranslateUi(spectWindow1)
        QtCore.QMetaObject.connectSlotsByName(spectWindow1)
        spectWindow1.setStyleSheet("QMainWindow{\n"
"\n"
"\n"
"\n"
"}\n"
"\n"

"QWidget\n"
"{\n"
"background-color:  #d4d5dd;"
"}\n"
"\n"
"")

    def retranslateUi(self, spectWindow1):
        _translate = QtCore.QCoreApplication.translate
        spectWindow1.setWindowTitle(_translate("spectWindow1", "Channel 1"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    spectWindow1 = QtWidgets.QWidget()
    ui = Ui_spectWindow1()
    ui.setupUi(spectWindow1)
    spectWindow1.show()
    sys.exit(app.exec_())
